main: github.AlpsBTE_Chat.AlpsBTE_Chat
version: 1.1
api-version: 1.12.2
name: AlpsBTE-Chat
author: R3tuxn

commands:
  chatReload:
    description: reload config
    usage: /chatReload
    permission: alpsbte.reload